from generator.mapping_utils.map_config_gen import MapConfigGen
from primitive.Prim_09_Router import Prim_09_Router
from primitive.Prim_41_Axon_CNN0_new import Prim_41_Axon
from itertools import product


class RouterInfoJsonGen(MapConfigGen):
    def __init__(self):
        super(RouterInfoJsonGen, self).__init__()

    @staticmethod
    def _get_group_id_by_core(map_config: dict, core_x_num=16, core_y_num=10):
        """
            original group_id = hash(((chip_x, chip_y), group_id))
        """
        group_cnt = 0
        group_id_by_core = dict()
        group_id_by_chip_and_old_group_id = []
        chip_phase_dict = MapConfigGen._get_used_chips(map_config)
        for ((chip_x_idx, chip_y_idx), step) in chip_phase_dict.keys():
            for group_idx in chip_phase_dict[((chip_x_idx, chip_y_idx), step)]:
                assert map_config[((chip_x_idx, chip_y_idx), 0)].get(group_idx) is not None
                assert hash(((chip_x_idx, chip_y_idx), group_idx)) not in group_id_by_chip_and_old_group_id
                group_id_by_chip_and_old_group_id.append(hash(((chip_x_idx, chip_y_idx), group_idx)))
                phase_group = map_config[((chip_x_idx, chip_y_idx), 0)][group_idx]
                for core_x_idx, core_y_idx in product(range(core_x_num), range(core_y_num)):
                    core_position = ((chip_x_idx, chip_y_idx), (core_x_idx, core_y_idx))
                    if phase_group.get(core_position) is None:
                        continue
                    group_id_by_core[core_position] = group_cnt
                group_cnt += 1
        return group_id_by_core

    @staticmethod
    def gen_router_info_json(map_config: dict, mode=0, core_x_num=16, core_y_num=10):
        """
            Extract router info from Python map_config, and generate Json
            Parameters:
                map_config: input map_config, generated by mapping
                mode: 0 - X first; 1 - Y first
                core_x_num:
                core_y_num:
            只支持不同group间相同顺序的phase之间的跨组同步
            即时原语请求和传输将被默认不进行
        """
        router_json = {
            "array_config": {
                "chip_w": 0,
                "chip_h": 0,
                "core_w": core_x_num,
                "core_h": core_y_num
            },
            "ROUTE_STRATEGY": mode,
            "optimize_goal": 0,
            "SYS_CLK_DIV": 0,
            "SERDES_CLK_DIV": 0,
            'phase_list': {}
        }
        group_id_by_core = RouterInfoJsonGen._get_group_id_by_core(map_config, core_x_num, core_y_num)
        chip_phase_dict = MapConfigGen._get_used_chips(map_config)

        max_chip_w, max_chip_h = 0, 0

        # generate router info Json
        for ((chip_x_idx, chip_y_idx), step) in chip_phase_dict.keys():
            max_chip_w = max(chip_x_idx, max_chip_w)
            max_chip_h = max(chip_y_idx, max_chip_h)
            for group_idx in chip_phase_dict[((chip_x_idx, chip_y_idx), step)]:
                assert map_config[((chip_x_idx, chip_y_idx), 0)].get(group_idx) is not None
                phase_group = map_config[((chip_x_idx, chip_y_idx), 0)][group_idx]
                for core_x_idx, core_y_idx in product(range(core_x_num), range(core_y_num)):
                    core_position = ((chip_x_idx, chip_y_idx), (core_x_idx, core_y_idx))
                    if phase_group.get(core_position) is None:
                        continue
                    prims = phase_group[core_position]['prims']
                    for phase_idx in range(len(prims)):
                        axon = prims[phase_idx]['axon']
                        if isinstance(axon, Prim_41_Axon):
                            a2s2_mode = 1 if axon.A2S2_mode else 0
                            a_time = 6 + 37 * ((axon.L4_num + 1) * a2s2_mode) + ((axon.L5_num + 1) * a2s2_mode)
                            # 6 + 37 * (L4 + 1) * (L5 + 1)
                        else:
                            a2s2_mode = 0
                            a_time = 0
                        router = prims[phase_idx]['router']
                        core_router_info_by_phase = {
                            "core_id": {
                                "chip_x": chip_x_idx, "chip_y": chip_y_idx, "core_x": core_x_idx, "core_y": core_y_idx
                            },
                            "old_core_id": {
                                "chip_x": chip_x_idx, "chip_y": chip_y_idx, "core_x": core_x_idx, "core_y": core_y_idx
                            },
                            "trigger": step,
                            "A2S2_mode": a2s2_mode,
                            "A_time": a_time,
                            "S1_time": 0,
                            "S2_time": 0,
                            "fixed_position": False,
                            "packets": []
                        }
                        if router is None:
                            core_router_info_by_phase['multicast_core'] = False
                            core_router_info_by_phase['multicast_dst'] = {
                                "chip_x": 0, "chip_y": 0, "core_x": 0, "core_y": 0
                            }
                        else:
                            core_router_info_by_phase['multicast_core'] = True if router.CXY else False
                            if router.CXY:
                                x, y, cx, cy = MapConfigGen._get_real_core_idx(core_x_idx + router.Nx,
                                                                               core_y_idx + router.Ny, chip_x_idx,
                                                                               chip_y_idx)
                            else:
                                x, y, cx, cy = 0, 0, 0, 0
                            core_router_info_by_phase['multicast_dst'] = {
                                "chip_x": cx, "chip_y": cy, "core_x": x, "core_y": y
                            }
                            for packet in router.send_destin_core_grp:
                                core_router_info_by_phase['packets'].append({
                                    "dst_core_id": {
                                        "chip_x": packet['core_id'][0][0][0],
                                        "chip_y": packet['core_id'][0][0][1],
                                        "core_x": packet['core_id'][0][1][0],
                                        "core_y": packet['core_id'][0][1][1]
                                    },
                                    "pack_num": packet['data_num'],
                                    "multicast_pack": True if len(packet['core_id']) > 1 else False
                                })
                        core_group = group_id_by_core[core_position]
                        if router_json['phase_list'].get(phase_idx) is None:
                            router_json['phase_list'][phase_idx] = {}
                        if router_json['phase_list'][phase_idx].get(core_group) is None:
                            router_json['phase_list'][phase_idx][core_group] = []
                        router_json['phase_list'][phase_idx][core_group].append(core_router_info_by_phase)
        router_json["array_config"]['chip_w'] = max_chip_w + 1
        router_json["array_config"]['chip_h'] = max_chip_h + 1
        return router_json
