from generator.mapping_utils.map_config_gen import MapConfigGen
from primitive.Prim_09_Router import Prim_09_Router
from itertools import product


class RouterInfoJsonGen(MapConfigGen):
    def __init__(self):
        super(RouterInfoJsonGen, self).__init__()

    @staticmethod
    def _get_group_id_by_core(map_config: dict, core_x_num=16, core_y_num=10):
        """
            original group_id = hash(((chip_x, chip_y), group_id))
        """
        group_id_by_core = dict()
        chip_phase_dict = MapConfigGen._get_used_chips(map_config)
        for ((chip_x_idx, chip_y_idx), step) in chip_phase_dict.keys():
            for group_idx in chip_phase_dict[((chip_x_idx, chip_y_idx), step)]:
                if map_config[((chip_x_idx, chip_y_idx), 0)].get(group_idx) is None:
                    continue
                phase_group = map_config[((chip_x_idx, chip_y_idx), 0)][group_idx]
                new_group_id = hash(((chip_x_idx, chip_y_idx), group_idx))
                for core_x_idx, core_y_idx in product(range(core_x_num), range(core_y_num)):
                    core_position = ((chip_x_idx, chip_y_idx), (core_x_idx, core_y_idx))
                    if phase_group.get(core_position) is None:
                        continue
                    group_id_by_core[core_position] = new_group_id
        return group_id_by_core

    @staticmethod
    def _get_data_exchange_group_id(router: Prim_09_Router, group_id_by_core: dict):
        groups = set({})
        if router is None:
            return groups
        for packet in router.recv_source_core_grp + router.send_destin_core_grp:
            if isinstance(packet['core_id'], tuple):
                groups.add(group_id_by_core[packet['core_id']])
            elif isinstance(packet['core_id'], list):
                for packet_core in packet['core_id']:
                    groups.add(group_id_by_core[packet_core])
            else:
                raise ValueError
        return groups

    @staticmethod
    def gen_router_info_json(map_config: dict, mode=0, core_x_num=16, core_y_num=10):
        """
            Extract router info from Python map_config, and generate Json
            Parameters:
                map_config: input map_config, generated by mapping
                mode: 0 - X first; 1 - Y first
                core_x_num:
                core_y_num:
            只支持不同group间相同顺序的phase之间的跨组同步
            即时原语请求和传输将被默认放在最后进行
        """
        router_json = {
            'mode': mode,
            'phase_list': {}
        }
        group_id_by_core = RouterInfoJsonGen._get_group_id_by_core(map_config, core_x_num, core_y_num)
        chip_phase_dict = MapConfigGen._get_used_chips(map_config)

        friend_groups = {}  # For every phase: [set of friend groups]
        for ((chip_x_idx, chip_y_idx), step) in chip_phase_dict.keys():
            for group_idx in chip_phase_dict[((chip_x_idx, chip_y_idx), step)]:
                if map_config[((chip_x_idx, chip_y_idx), 0)].get(group_idx) is None:
                    continue
                phase_group = map_config[((chip_x_idx, chip_y_idx), 0)][group_idx]
                for phase_idx in range(32):  # Max number of phases
                    set_of_one_group_one_phase = {hash(((chip_x_idx, chip_y_idx), group_idx))}
                    phase_exist = False
                    for core_x_idx, core_y_idx in product(range(core_x_num), range(core_y_num)):
                        core_position = ((chip_x_idx, chip_y_idx), (core_x_idx, core_y_idx))
                        if phase_group.get(core_position) is None:
                            continue
                        prims = phase_group[core_position]['prims']
                        if len(prims) <= phase_idx:
                            continue
                        phase_exist = True
                        # 先遍历一个group自己和所有数据交换的group，然后把他们写成一个set，最终逐个set去合并
                        # ergodic router receive source core and send destination core
                        router = prims[phase_idx]['router']
                        set_of_one_group_one_phase |= RouterInfoJsonGen._get_data_exchange_group_id(router,
                                                                                                    group_id_by_core)
                    if phase_exist:
                        if friend_groups.get(phase_idx) is None:
                            friend_groups[phase_idx] = []
                        friend_groups[phase_idx].append(set_of_one_group_one_phase)

        group_corr = {}     # For every phase: old group -> new group
        for phase_idx, value in friend_groups.items():
            for i in range(len(value)):
                j = i + 1
                while j < len(value):
                    if len(value[i] & value[j]) > 0:
                        value[i] |= value[j]
                        del value[j]
                    else:
                        j += 1
        for phase_idx, value in friend_groups.items():
            group_corr[phase_idx] = {}
            for i in range(len(value)):
                for item in value[i]:
                    group_corr[phase_idx][item] = i

        # generate router info Json
        for ((chip_x_idx, chip_y_idx), step) in chip_phase_dict.keys():
            for group_idx in chip_phase_dict[((chip_x_idx, chip_y_idx), step)]:
                if map_config[((chip_x_idx, chip_y_idx), 0)].get(group_idx) is None:
                    continue
                phase_group = map_config[((chip_x_idx, chip_y_idx), 0)][group_idx]
                for core_x_idx, core_y_idx in product(range(core_x_num), range(core_y_num)):
                    core_position = ((chip_x_idx, chip_y_idx), (core_x_idx, core_y_idx))
                    if phase_group.get(core_position) is None:
                        continue
                    prims = phase_group[core_position]['prims']
                    for phase_idx in range(len(prims)):
                        router = prims[phase_idx]['router']
                        core_router_info_by_phase = {
                            "core_id": {
                                "chip_x": chip_x_idx, "chip_y": chip_y_idx, "core_x": core_x_idx, "core_y": core_y_idx
                            },
                            "packets": []
                        }
                        if router is None:
                            core_router_info_by_phase['multicast_core'] = False
                            core_router_info_by_phase['multicast_dst'] = {
                                "chip_x": 0, "chip_y": 0, "core_x": 2, "core_y": 0
                            }
                        else:
                            core_router_info_by_phase['multicast_core'] = router.CXY
                            x, y, cx, cy = MapConfigGen._get_real_core_idx(core_x_idx + router.Nx,
                                                                           core_y_idx + router.Ny, chip_x_idx,
                                                                           chip_y_idx)
                            core_router_info_by_phase['multicast_dst'] = {
                                "chip_x": cx, "chip_y": cy, "core_x": x, "core_y": y
                            }
                            for packet in router.send_destin_core_grp:
                                core_router_info_by_phase['packets'].append({
                                    "dst_core_id": {
                                        "chip_x": packet['core_id'][0][0][0],
                                        "chip_y": packet['core_id'][0][0][1],
                                        "core_x": packet['core_id'][0][1][0],
                                        "core_y": packet['core_id'][0][1][1]
                                    },
                                    "pack_num": packet['data_num'],
                                    "multicast_pack": True if len(packet['core_id']) > 1 else False
                                })
                        core_group = group_corr[phase_idx][group_id_by_core[core_position]]
                        if router_json['phase_list'].get(phase_idx) is None:
                            router_json['phase_list'][phase_idx] = {}
                        if router_json['phase_list'][phase_idx].get(core_group) is None:
                            router_json['phase_list'][phase_idx][core_group] = []
                        router_json['phase_list'][phase_idx][core_group].append(core_router_info_by_phase)
        return router_json
